plugins {
    id("com.android.application")
    id("kotlin-android")
    id("dev.flutter.flutter-gradle-plugin")
}

import java.util.Properties
import java.io.FileInputStream

// Load keystore properties
val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}

android {
    namespace = "com.textfixer.android"
    compileSdk = 35

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    defaultConfig {
        applicationId = "com.textfixer.android"
        minSdk = flutter.minSdkVersion
        targetSdk = 35
        versionCode = 6
        versionName = "2.5.0"

        // Disable native library splits to prevent CMake triggering
        ndk {
            abiFilters.clear()
        }
    }

    buildFeatures {
        // Disable all native build features
        prefab = false
        aidl = false
        renderScript = false
        buildConfig = true
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = false
        }
    }

    // CRITICAL: Signing configuration
    signingConfigs {
        create("release") {
            keyAlias = keystoreProperties["keyAlias"] as String? ?: ""
            keyPassword = keystoreProperties["keyPassword"] as String? ?: ""
            storeFile = file(keystoreProperties["storeFile"] as String? ?: "")
            storePassword = keystoreProperties["storePassword"] as String? ?: ""
        }
    }

    buildTypes {
        getByName("debug") {
            // Debug build type configuration
        }

        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            signingConfig = signingConfigs.getByName("release")
            ndk {
                debugSymbolLevel = "FULL"
            }
        }
    }

    // DO NOT add externalNativeBuild block - it triggers CMake detection
}

flutter {
    source = "../.."
}

// Disable CMake tasks that are auto-generated by AGP/Flutter plugin
tasks.configureEach {
    if (name.contains("CMake", ignoreCase = true)) {
        enabled = false
    }
}
